name: fboss
version: 0.3.0
summary: Facebook Open Switching System
description: Facebook's software stack for controlling and managing network switches
confinement: devmode
grade: devel

apps:
  wedge-agent:
    command: start_wedge_agent
    daemon: simple
    plugs: 
      - network
      - network-bind
      - network-control
      - network-observe

  fboss-route:
    command: fboss_route.py
    plugs:
      - network
      - network-bind
      - network-control
      - network-observe

parts:
  fboss:
    plugin: fboss
    build-packages:
      - pkg-config
      - iptables-dev
      - libselinux1-dev
      - xtables-addons-source
      - texlive-latex-base
      - linuxdoc-tools
      - bison
      - autoconf
      - autoconf-archive
      - cmake
      - flex
      - automake
      - libdb5.3-dev
      - libtool
      - libssl-dev
      - libboost-all-dev
      - python-dev
      - libgflags-dev
      - libgoogle-glog-dev
      - libdouble-conversion-dev
      - libevent-dev
      - libsnappy-dev
      - libkrb5-dev
      - libsasl2-dev
      - libcurl4-nss-dev
      - libnl-3-dev
      - libpcap-dev
      - libnl-route-3-dev
      - libnuma-dev
      - libi2c-dev
      - libusb-1.0-0-dev
      - make
      - zip 
      - git
      - g++
      - scons
      - liblz4-dev
      - liblzma-dev
      - zlib1g-dev
      - binutils-dev
      - libjemalloc-dev
      - libiberty-dev

  fboss-launcher:
    plugin: dump
    source: src/
    organize:
      start_wedge_agent: bin/start_wedge_agent

  fboss-config:
    plugin: dump
    source: config/
    organize:
      ocp-demo.json: config/ocp-demo.json

