#!/bin/sh

wedge_agent \
    -persistent_state_dir=$SNAP_DATA/state \
    -volatile_state_dir=$TMPDIR \
    -fruid_filepath=$TMPDIR/fruid.json \
    -mgmt_if=eth0 \
    -can_warm_boot=false \
    -config=$SNAP/config/ocp-demo.json
